puddle/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from . import forms


app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("contact/",views.contact, name="contact" ),
    path("signup/", views.signup, name="signup"),
    path("login/", auth_views.LoginView.as_view(authentication_form=forms.LoginForm, template_name="core/login.html"), name="login")

    
]

puddle/dashboard/urls.py
from django.urls import path
from .views import index

app_name = "dashboard"

urlpatterns = [
    path("", index, name="index" )
]

puddle/item/urls.py
from django.urls import path
from .views import detail, addNewItem, delete, editItem, items

app_name = "item"

urlpatterns = [
    path("", items, name="items"),
    path("<int:item_id>/", detail, name="detail"),
    path("<int:item_id>/delete", delete, name="delete"),
    path("int:item_id/edit", editItem, name="edit"),
    path("new/", addNewItem, name="new_item")
]

puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index, contact

# For dev
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls")),
    path("items/", include("item.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/dashboard/models.py
from django.db import models

# Create your models here.

puddle/item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to="item_images", blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name="item", on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name="items", on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name

puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder':  "Your username",
            'class': "w-full px-6 py-4 rounded-xl"
        }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder':  "Your password",
            'class': "w-full px-6 py-4 rounded-xl"
        }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

        username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder':  "Your username",
            'class': "w-full px-6 py-4 rounded-xl"
        }))

        email = forms.CharField(widget=forms.EmailInput(attrs={
            'placeholder':  "Your email",
            'class': "w-full px-6 py-4 rounded-xl"
        }))

        password1 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder':  "Your password",
            'class': "w-full px-6 py-4 rounded-xl"
        }))
        password2 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder':  "Confirm password",
            'class': "w-full px-6 py-4 rounded-xl"
        }))

puddle/core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm
# Create your views here.

def index(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    return render(request, "core/index.html", {
        'categories': categories,
        'items': items
    })
    
def contact(request):
    return render(request, "core/contact.html")

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("/login/")
        else: 
            print(form)
    else:
        form = SignupForm()
        return render(request, "core/signup.html", {
            'form': form
        })
    

puddle/dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from item.models import Item
# Create your views here.

@login_required
def index(request):
    items = Item.objects.filter(created_by=request.user)

    return render(request, "dashboard/index.html", {
        'items': items
    })

puddle/item/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .form import AddItemForm, EditItemForm
# Create your views here.
from .models import Item, Category


def detail(request, item_id):
    item = get_object_or_404(Item, pk=item_id)
    same_category_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=item_id)[0:3]
    return render(request, "item/detail.html", {
        "item": item,
        "same_category_items": same_category_items
    })


@login_required
def addNewItem(request):
    if request.method == "POST":
        form = AddItemForm(request.POST, request.FILES)
        item = form.save(commit=False)
        item.created_by = request.user
        item.save()
        return redirect("item:detail", item_id=item.id)

    else:
        form = AddItemForm()

        return render(request, "item/form.html", {
            'form': form,
            'title': "New Item"
        })


def items(request):
    query = request.GET.get('query', '')
    items = Item.objects.filter(is_sold=False)
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    if query:
        items = items.filter(Q(name__icontains=query) | Q(description_icontains=query))

    return render(request, 'item/browse.html', {
        "items": items,
        "query": query,
        "categories": categories,
        "category_id": int(category_id)
    })


@login_required
def editItem(request, item_id):
    item = get_object_or_404(Item, pk=item_id, created_by=request.user)
    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item)
        form.save()

        return redirect("item:detail", item_id=item.id)

    else:
        form = EditItemForm(instance=item)

        return render(request, "item/form.html", {
            'form': form,
            'title': "Edit Item"
        })


@login_required
def delete(request, item_id):
    item = get_object_or_404(Item, pk=item_id, created_by=request.user)
    item.delete()

    return redirect("dasboard:index")

puddle/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="http://cdn.tailwindcss.com"></script>
    <title>{% block title %} {% endblock %}| Puddle</title>
</head>
<body>
    <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Puddle</a>
        <div class="spacex-6">
            
            <a href="{% url 'item:new_item'%}" class="text-l font-semibold hover:text-gray-500">New item</a>
            <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

            {% if request.user.is_authenticated%}
            
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>

            {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6 ">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="px-6 py-6 flex justify-between bg-gray-800">
        <div class="w2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-500">About</h3>
        </div>
        <div class="w1/3">
            <h3 class="mb-5 font-semibold text-gray-500">Menu</h3>
            <ul class="space-y-2">
                <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li> <a href="{%url 'core:contact'%}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy</a></li>
                <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

puddle/core/templates/core/contact.html
{% extends "core/base.html" %}
{% block title%} Contact {% endblock %}

{% block content%}
    <h1>The contact page</h1>
{% endblock%}

puddle/core/templates/core/index.html
{% extends "core/base.html" %}
{% block title%} Welcome {% endblock %}

{% block content %}
    <div class="px-6 mt-6 rounded-xl py-12 bg-gray-100">
        <h2 class="mb-12 text-2xl text-center">New items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items%}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div><img src="{{item.image.url}}" alt="" class="rounded-t-xl"></div>
                    </a>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2>
                        <p class="text-gray-500">Price: {{item.price}}</p>
                    </div>
                </div>
            {% endfor %}
               
        </div>
    </div>
    <div class="px-6 mt-6 rounded-xl py-12 bg-gray-100">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories%}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{category.name}}</h2>
                            <p class="text-gray-500">{{category.items.count}} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
               
        </div>
    </div>
{% endblock %}

puddle/core/templates/core/login.html
{% extends "core/base.html" %}
{% block title%} Log in {% endblock %}
{% block content %}
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="text-3xl mb-6">Log in</h1>

        <form action="." method="post">
            {% csrf_token %}

            <div>
                <label class="inline-block mb-2" >Username</label><br/>
                {{form.username}}
            </div>
    
            <div>
                <label class="inline-block mb-2" >Password</label><br/>
                {{form.password}}
            </div>
            
            {{form.non_field_errors}}
            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-
            500 rounded-xl">
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
                {{form.non_field_errors}}
            </div>
            {% endif %}

            <button class="px-8 py-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
            

        </form>
    </div>
{% endblock %}

puddle/core/templates/core/signup.html
{% extends "core/base.html" %}
{% block title%} Sign Up {% endblock %}
{% block content %}
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="text-3xl mb-6">Signup</h1>

        <form action="." method="post">
            {% csrf_token %}

            <div>
                <label class="inline-block mb-2" >Username</label><br/>
                {{form.username}}
            </div>
            <div>
                <label class="inline-block mb-2" >Email</label><br/>
                {{form.email}}
            </div>
            <div>
                <label class="inline-block mb-2" >Password</label><br/>
                {{form.password1}}
            </div>
            <div>
                <label class="inline-block mb-2" >Confirm password</label><br/>
                {{form.password2}}
            </div>
            {{form.non_field_errors}}
            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-
            500 rounded-xl">
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
                {{form.non_field_errors}}
            </div>
            {% endif %}

            <button class="px-8 py-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
            

        </form>
    </div>
{% endblock %}

puddle/dashboard/templates/dashboard/index.html
{% extends "core/base.html" %}
{% block title%} Welcome {% endblock %}

{% block content %}
    <div class="px-6 mt-6 rounded-xl py-12 bg-gray-100">
        <h2 class="mb-12 text-2xl text-center">My items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in items%}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div><img src="{{item.image.url}}" alt="" class="rounded-t-xl"></div>
                    </a>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2>
                        <p class="text-gray-500">Price: {{item.price}}</p>
                    </div>
                </div>
            {% endfor %}
               
        </div>
    </div>
{% endblock %}

puddle/item/templates/item/browse.html
{% extends 'core/base.html' %}

{% block title %} Items {% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form action="{% url 'item:items' %}" method="get">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find chair, bike, car, or anything"  >
                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>
            <hr class="my-6">
            <p class="font-semibold">Categories</p>
            <ul>
                
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl {% if category.id == category_id%} bg-gray-200 {%endif%}">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }} </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for item in items%}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div><img src="{{item.image.url}}" alt="" class="rounded-t-xl"></div>
                        </a>
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{item.name}}</h2>
                            <p class="text-gray-500">Price: {{item.price}}</p>
                        </div>
                    </div>
                {% endfor %}
                   
            </div>
        </div>
    </div>
{% endblock %}

puddle/item/templates/item/detail.html
{% extends "core/base.html" %}

{% block title %} {{item.name}} {% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-5">
        <div class="col-span-3"><img class="rounded-xl" src="{{item.image.url}}" alt=""></div>

        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl">
                {{ item.name }}
            </h1>
            <p class="text-gray-500"><strong>Price:</strong>{{item.price}}</p>
            <p class="text-gray-500"><strong>Seller:</strong>{{ item.created_by }}</p>
            {% if item.description%}
                <p class="text-gray-700"><strong class="text-gray-500">Description:</strong><br/>{{ item.description }}</p>
            {% endif %}

            {% if request.user == item.created_by%}
                <div class="mt-6 p-6 bg-white rounded-xl">
                    <p>This is your item!</p>
                    <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-white font-semibold bg-teal-500 text-lg rounded-xl">Edit</a>
                    <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-white font-semibold bg-red-500 text-lg rounded-xl">Delete</a>
                </div>
            {% else %}
                <a href="#" class="inline-block mt-6 px-6 py-3 font-semibold bg-teal-500 text-white text-lg rounded-xl hover:bg-teal-700">Contact seller</a>
            {% endif %}
        </div>
        
    </div>
    <div class="px-6 mt-6 rounded-xl py-12 bg-gray-100">
        <h2 class="mb-12 text-2xl text-center">Related Items</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in same_category_items%}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div><img src="{{item.image.url}}" alt="" class="rounded-t-xl"></div>
                    </a>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2>
                        <p class="text-gray-500">Price: {{item.price}}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

puddle/item/templates/item/form.html
{% extends "core/base.html" %}

{% block title %} {{title}} {% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl ">{{title}}</h1>
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="space-y-4">
            {{form.as_p}}

        </div>
        {{form.non_field_errors}}
            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-
            500 rounded-xl">
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}
                {{form.non_field_errors}}
            </div>
            {% endif %}

            <button class=" mt-6 px-8 py-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
{% endblock %}